### ISSUE TITLE
Libtwenty error

### ISSUE THREAD

**Issue by SlumberDemon** [Z1R343L/libtwenty#3]
```py
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.9/site-packages/disnake/ext/commands/core.py", line 169, in wrapped
    ret = await coro(*args, **kwargs)
  File "/app/src/commands/Fun.py", line 232, in _twozerofoureight
    im = b.render()
  File "/app/.heroku/python/lib/python3.9/site-packages/libtwenty/__init__.py", line 131, in render
    tiles = t_cache.get(self.tile_size) or prep_tiles(tile_size=self.tile_size, tile_outline=tile_outline)
NameError: name 't_cache' is not defined

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.9/site-packages/disnake/ext/commands/bot_base.py", line 570, in invoke
    await ctx.command.invoke(ctx)
  File "/app/.heroku/python/lib/python3.9/site-packages/disnake/ext/commands/core.py", line 920, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/app/.heroku/python/lib/python3.9/site-packages/disnake/ext/commands/core.py", line 178, in wrapped
    raise CommandInvokeError(exc) from exc
disnake.ext.commands.errors.CommandInvokeError: Command raised an exception: NameError: name 't_cache' is not defined
```

**Comment by Z1R343L** [comment]
should be fixed now

**Comment by SlumberDemon** [comment]
ok
